version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"       # Puerto AMQP
      - "15672:15672"     # Puerto de la interfaz de gestión
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - task-network

volumes:
  mysql-data:

networks:
  task-network:
    driver: bridge
